### PR TITLE
Use async_register instead of async_register_admin_service

### PR DESCRIPTION
**Pull request by Azelphur**
With the use of async_register_admin_service, only administrator accounts can use these features. I bumped into this issue where non-admin users were unable to trigger door unlock.

This patch resolves that issue, but may not be the best way of doing it. If the use of async_register_admin_service was intentional, perhaps some way to allow non admin users access would be handy.

### CODE REVIEW

**Comment by myhomeiot** [comment]
Thanks for contribution!

If I add additional configuration param for example admin_only_services and by default it's will be true it's will be more useful?

**Comment by Azelphur** [comment]
Sure, that would solve it for me.

**Comment by Azelphur** [comment]
Hi, have updated my PR, I think this is the correct way to handle permissions, it's documented [here](https://developers.home-assistant.io/docs/auth_permissions/#checking-entity-permissions) and be configured as detailed [here](https://developers.home-assistant.io/blog/2019/03/11/user-permissions/)

This should allow users to have the permissions however they want, in theory :)

**Comment by myhomeiot** [comment]
@azelphur thanks for information! I check Home Assistant Core code and add user permission checks in the same way how they did it.
I was check it according [article](https://developers.home-assistant.io/blog/2019/03/11/user-permissions) which you points me, and it's works! ;-)
Please update to the [lattest](https://github.com/myhomeiot/DahuaVTO/releases) version and let's me know if it's works for you.
Thanks in advance.

**Comment by Azelphur** [comment]
Doesn't work for me, tried running:

```
service: dahua_vto.open_door
data:
  entity_id: sensor.doorbell
  channel: 1
  short_number: HA
```

and nothing happens. Nothing in the logs either. Done a little debugging, it seems DahuaVTO.async_open_door never gets called.

**Comment by myhomeiot** [comment]
Very strange, check it again, works. `sensor.doorbell` in OK state and has `deviceType` and `serialNumber` attributes?
Do you change user group permissions or you did test under user with admin rights?

**Comment by Azelphur** [comment]
sensor.doorbell has state "OK" and attributes:
- deviceType: VTO2202F
- serialNumber: 7A01...
- friendly_name: Doorbell

Tested with both admin and normal user, in both cases nothing happens. If I revert your most recent commit and restart home assistant, it works (only as an admin user)

**Comment by myhomeiot** [comment]
Very strange, which version of Home Assistant do you have?
I test it with 2021.9, just updates integration using HACS and all works as with previous version.

**Comment by Azelphur** [comment]
I'm using 2021.9.2, for reference I run home assistant (core only), using docker, and I have added this component manually (no HACS).

If it helps, I'm on the official home assistant discord, we could chat there and try and debug it.

**Comment by Azelphur** [comment]
This is resolved in the most recent release, thanks again :)

**Pull request closed without merging**
